import Link from "next/link";
import { ArrowUpRight, Database, Flask, GitBranch, MapPin, Sparkle } from "@phosphor-icons/react/dist/ssr";

export default function HomePage() {
  return (
    <main>
      <nav className="site-nav page-shell"><Link href="/" className="brand"><span className="brand-mark">S</span><span>SolGeo / field notes</span></Link><div className="nav-links"><Link href="/case-studies/abu-dhabi-urban-edge/">Case study</Link><Link href="/research/">Research</Link><Link href="/reproduce/">Reproduce</Link></div></nav>
      <section className="home-hero page-shell"><div className="hero-kicker"><span className="status-dot" /> reproducible earth observation / v0.1</div><h1>Make satellite change<br /><em>auditable.</em></h1><p className="home-lead">SolGeo turns free satellite data into evidence you can inspect, reproduce, and explain. This first case asks whether annual learned representations help humans find persistent urban-edge change in Abu Dhabi.</p><div className="hero-actions"><Link className="button button-dark" href="/case-studies/abu-dhabi-urban-edge/">Explore the case <ArrowUpRight size={17} /></Link><Link className="text-link" href="/research/">See the research question</Link></div><div className="hero-index"><span>01</span><span>signal → context → review</span><span>Abu Dhabi / UAE</span></div></section>
      <section className="home-grid page-shell"><div className="home-grid-label"><p className="eyebrow">A learning project with a research standard</p><p>Every output is paired with provenance, uncertainty, and a next action for the analyst.</p></div><article className="feature-card feature-card-dark"><div className="feature-icon"><MapPin size={21} /></div><span className="card-index">01 / live direction</span><h2>Urban edge, not black-box magic.</h2><p>Compare seasonal Sentinel-2 evidence with AlphaEarth annual embeddings, then inspect where the two signals agree or disagree.</p><Link href="/case-studies/abu-dhabi-urban-edge/" className="card-link">Open Abu Dhabi case <ArrowUpRight size={16} /></Link></article><article className="feature-card"><div className="feature-icon"><Flask size={21} /></div><span className="card-index">02 / research posture</span><h2>Claims have gates.</h2><p>The public preview is deliberately locked until real imagery and independently reviewed labels support an accuracy claim.</p><Link href="/research/" className="card-link">Read the boundaries <ArrowUpRight size={16} /></Link></article></section>
      <section className="principles page-shell"><div><p className="eyebrow">What you will learn</p><h2>From pixels to a<br /><em>defensible result.</em></h2></div><div className="principle-list"><div><Database size={20} /><span><strong>Data contracts</strong><small>STAC search, QA, grids, nodata, manifests</small></span></div><div><Sparkle size={20} /><span><strong>Representation learning</strong><small>embeddings as evidence, not a magic label</small></span></div><div><GitBranch size={20} /><span><strong>Reusable engineering</strong><small>small modules, tests, CLI, notebooks, web</small></span></div></div></section>
      <footer className="site-footer page-shell"><span>SolGeo / a portfolio research instrument</span><span>Built to be read, rerun, and questioned.</span></footer>
    </main>
  );
}
